### ISSUE TITLE
Dios mio que materia de mierda

### ISSUE THREAD

**Issue by BrunoMollo** [adrielgorosito/Prolog-IA#2]
No entiendo una goma de este lenguaje, posta amigo que la estoy viendo re negra a la situacion

![image](https://github.com/user-attachments/assets/c6528ab8-b1aa-4aa4-920c-f565802f8e2d)

**Comment by adrielgorosito** [comment]
yyy es todo un tema vio?

**Comment by BrunoMollo** [comment]
AIUDAAAAA
